01-18 11:19:19 rover.rover  INFO_QUIET Waiting For 1 Minute Before Checking For New Tweets
01-18 11:20:19 archiver.archiver INFO_QUIET Checking For New Tweets
01-18 11:20:19 archiver.archiver INFO_QUIET Checking For Tweets From Donald Trump - @POTUS
01-18 11:20:20 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:20 archiver.archiver INFO_QUIET Checking For Tweets From Joseph Biden - @JoeBiden
01-18 11:20:20 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:20 archiver.archiver INFO_QUIET Checking For Tweets From Joseph Biden - @Transition46
01-18 11:20:21 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:21 archiver.archiver INFO_QUIET Checking For Tweets From Michael Pence - @vp
01-18 11:20:21 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:21 archiver.archiver INFO_QUIET Checking For Tweets From Michael Pence - @mike_pence
01-18 11:20:22 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:22 archiver.archiver INFO_QUIET Checking For Tweets From Kamala Harris - @senkamalaharris
01-18 11:20:22 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:22 archiver.archiver INFO_QUIET Checking For Tweets From Kamala Harris - @KamalaHarris
01-18 11:20:23 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:23 archiver.archiver INFO_QUIET Checking For Tweets From Joseph Biden - @PresElectBiden
01-18 11:20:23 archiver.archiver INFO_QUIET No New Tweets Found
01-18 11:20:24 archiver.archiver INFO_QUIET Waiting For 1 Minute Before Checking For New Tweets
01-18 11:20:24 rover.rover  INFO_QUIET Checking For New Tweets
Exception in thread Rover:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/alexis/Rover/rover/rover.py", line 61, in run
    self.look_for_tweets()
  File "/home/alexis/Rover/rover/rover.py", line 83, in look_for_tweets
    replied_to_status = self.process_tweet(latest_status=last_replied_status)
  File "/home/alexis/Rover/rover/rover.py", line 96, in process_tweet
    mentions: Reversible[json] = api.GetMentions(since_id=latest_status)
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 3570, in GetMentions
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 4962, in _RequestUrl
    limit = self.CheckRateLimit(url)
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 4809, in CheckRateLimit
    self.InitializeRateLimit()
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 4792, in InitializeRateLimit
    data = self._ParseAndCheckTwitter(resp.content.decode('utf-8'))
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 4908, in _ParseAndCheckTwitter
    self._CheckForTwitterError(data)
  File "/home/alexis/.local/lib/python3.9/site-packages/twitter/api.py", line 4928, in _CheckForTwitterError
    raise TwitterError(data['errors'])
twitter.error.TwitterError: [{'message': 'Over capacity', 'code': 130}]